FROM node:16-alpine as build
RUN mkdir /app
COPY package.json yarn.lock /app/
WORKDIR /app
RUN yarn
COPY . .
RUN yarn build

FROM alpine
RUN apk add thttpd
RUN mkdir /app
WORKDIR /app
COPY --from=build /app/dist .
CMD ["thttpd", "-D", "-h", "0.0.0.0", "-p", "4100"]
